version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yeahThisIsNotSecure
      POSTGRES_DB: nest
    networks:
      - prospect
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yeahThisIsNotSecure
      POSTGRES_DB: nest-test-db
    networks:
      - prospect
networks:
  prospect:
